### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by 0xRZ** [rmagatti/goto-preview#48] opened 2021-11-27 18:19 UTC
Hello, thank you for the plugin. However, there is one thing that is weird to me. After i close the preview window with already existing before hidden buffer, the buffer is unloaded. As i understand noone reported this before, which is wierd, is it possible to fix this? Im on the latest neovim master.

**Comment by rmagatti** [comment] 2021-11-28 04:01
Hey, thanks for the submission.

I'm a little unsure of what you mean though. Could you maybe elaborate?

**Comment by 0xRZ** [comment] 2021-11-28 07:44
@rmagatti Okay. Here is a gif of what i mean:
![Peek 2021-11-28 10-40](https://user-images.githubusercontent.com/46892933/143734043-c98a74a6-6472-4305-9475-6acd1e1b1844.gif)

You see after i close goto-preview window with a definition of the `TEST` macro, previously loaded buffer `common.h` is unloaded.

Files i use to reproduce:
#### **`init.vim`**
```vim
call plug#begin() 
     Plug 'neovim/nvim-lspconfig'
     Plug 'rmagatti/goto-preview'
call plug#end()

lua << EOF
      require'lspconfig'.clangd.setup{}
      require('goto-preview').setup{}
EOF

nnoremap gf <cmd>lua vim.lsp.buf.definition()<CR>
nnoremap gpd <cmd>lua require('goto-preview').goto_preview_definition()<CR>
nnoremap gP <cmd>lua require('goto-preview').close_all_win()<CR>
```
#### **`common.h`**
```c
#define TEST 1
```
#### **`test.c`**
```c
#include "common.h"

int main (int argc, char *argv[])
{
        int a = 1 + TEST;
        return 0;
}
```

**Comment by rmagatti** [comment] 2021-11-28 21:36
Assuming you're closing the preview window through the goto-preview mapping. This is what the documentation about the function I use to close it says.
```lua
-- Closes the window (like |:close| with a |window-ID|).
--- @param window window #Window handle, or 0 for current window
--- @param force boolean #Behave like `:close!` The last window of a
---               buffer with unwritten changes can be closed. The
---               buffer will become hidden, even if 'hidden' is
---               not set.
function vim.api.nvim_win_close(window, force) end
```

And this is how I'm calling it.
`vim.api.nvim_win_close(win_handle, true)`

I'm adding an option to not force close in a PR as I think this is likely the cause of what you're seeing, i.e I think your buffer is becoming hidden.

**Comment by rmagatti** [comment] 2021-11-28 21:38
@0xRZ would you mind testing out the changes by installing with the branch of the PR linked here and setting `force_close = false` in the setup?

**Comment by 0xRZ** [comment] 2021-11-29 08:47
@rmagatti i pulled `add-force-close-option`, tried to set `force_close = false` but it doesn't fix anything for me, `<cmd>lua require('goto-preview').close_all_win()<CR>` still unloads buffer after preview window is closed :man_shrugging: 
Im not really sure what this `force` parameter of `nvim_win_close` do, but i found out that https://github.com/rmagatti/goto-preview/blob/main/lua/goto-preview/lib.lua#L130 `bufhidden` option can be changed from `wipe` to `hide`, that way existing buffer won't be unloaded, imo it seems to be the correct behaviour. Though i think (?) there can be added logic to check if buffer to open is already loaded before opening floating goto-preview window and use `hide` parameter only in this case and `wipe` in others, this way newly opened buffers for the first time won't clutter up buffer list.

**Comment by rmagatti** [comment] 2021-11-29 17:38
Oh interesting. Good find. I'll add an option for that to too.

**Comment by rmagatti** [comment] 2021-11-29 20:03
@0xRZ added the option to change bufhidden too. Lmk if that works for you.

**Comment by 0xRZ** [comment] 2021-11-29 20:12
@rmagatti yeah, just pulled `add-force-close-option`, when specifying `bufhidden = "hide",` buffers are not lost. thx

**Closed** 2021-11-29 20:39 UTC
Labels: bug
